### ISSUE TITLE
Provide a way to unit test code fixes (fix all)

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonarlint-vs#196]

**Comment by dbolkensteyn** [comment]
This isn't working in all cases, for example when using the following codefix for the empty statement:
```
context.RegisterCodeFix(
	CodeAction.Create(
		Title,
		c =>
		{
			var oldParent = syntaxNode.Parent;
			var newParent = oldParent.RemoveNode(syntaxNode, SyntaxRemoveOptions.KeepExteriorTrivia).WithAdditionalAnnotations(Formatter.Annotation);
			var newRoot = root.ReplaceNode(oldParent, newParent);
			return Task.FromResult(context.Document.WithSyntaxRoot(newRoot));
		},
		null),
	context.Diagnostics.Single());
```

the code fixer unit test framework fails with:

```
Test Name:	EmptyStatement_CodeFix
Test FullName:	SonarLint.UnitTest.Rules.EmptyStatementTest.EmptyStatement_CodeFix
Test Source:	C:\Users\dinesh\Desktop\sonarsource\sonarlint-vs\src\Tests\SonarLint.UnitTest\Rules\EmptyStatementTest.cs : line 39
Test Outcome:	Failed
Test Duration:	0:00:01,26052

Result StackTrace:	
at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.WhileStatement(SyntaxToken whileKeyword, SyntaxToken openParenToken, ExpressionSyntax condition, SyntaxToken closeParenToken, StatementSyntax statement)
   at Microsoft.CodeAnalysis.CSharp.Syntax.WhileStatementSyntax.Update(SyntaxToken whileKeyword, SyntaxToken openParenToken, ExpressionSyntax condition, SyntaxToken closeParenToken, StatementSyntax statement)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitWhileStatement(WhileStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.WhileStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.RemoveNodes[TRoot](TRoot root, IEnumerable`1 nodes, SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.RemoveNodesCore(IEnumerable`1 nodes, SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode[TRoot](TRoot root, SyntaxNode node, SyntaxRemoveOptions options)
   at SonarLint.Rules.EmptyStatementCodeFixProvider.<>c__DisplayClass4_0.<RegisterCodeFixesAsync>b__0(CancellationToken c) in C:\Users\dinesh\Desktop\sonarsource\sonarlint-vs\src\SonarLint\Rules\EmptyStatementCodeFixProvider.cs:line 64
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<ComputeOperationsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetOperationsCoreAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetOperationsAsync>d__4.MoveNext()
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SonarLint.UnitTest.Verifier.ApplyCodeFix(Document document, CodeAction codeAction) in C:\Users\dinesh\Desktop\sonarsource\sonarlint-vs\src\Tests\SonarLint.UnitTest\Verifier.cs:line 174
   at SonarLint.UnitTest.Verifier.VerifyCodeFix(String path, String pathToExpected, DiagnosticAnalyzer diagnosticAnalyzer, CodeFixProvider codeFixProvider, String codeFixTitle) in C:\Users\dinesh\Desktop\sonarsource\sonarlint-vs\src\Tests\SonarLint.UnitTest\Verifier.cs:line 82
   at SonarLint.UnitTest.Rules.EmptyStatementTest.EmptyStatement_CodeFix() in C:\Users\dinesh\Desktop\sonarsource\sonarlint-vs\src\Tests\SonarLint.UnitTest\Rules\EmptyStatementTest.cs:line 40
Result Message:	
Test method SonarLint.UnitTest.Rules.EmptyStatementTest.EmptyStatement_CodeFix threw exception: 
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: statement
```

**Comment by dbolkensteyn** [comment]
Relates to https://github.com/dotnet/roslyn/issues/3409

**Comment by tvsonar** [comment]
@dbolkensteyn We should check out the `VerifyFixAllAsync()` in https://github.com/code-cracker/code-cracker/blob/b4e2060894506f7ec959ced727f05891c2ecd70a/test/Common/CodeCracker.Test.Common/Verifiers/CodeFixVerifier.cs, which provides a way to test "FixAll" issues.
