### ISSUE TITLE
SonarLint 1.6.0 - AD0001 Analyzer 'SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams' exception

### ISSUE THREAD

**Issue by wilhelmmedetz** [SonarSource/sonarlint-vs#723]
Severity	Code	Description	Project	File	Suppression State	Detail Description
Warning	AD0001	Analyzer 'SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	SimControl.Samples.CSharp.ClassLibrary40.Tests		Active	Analyzer 'SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams' threw the following exception:
'System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.Last[T](ImmutableArray`1 immutableArray)
   at SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams.<>c.<CheckCall>b__11_4(IMethodSymbol m) in C:\SourcesTv\temp\sonarlint-vs\src\SonarLint.CSharp\Rules\InvocationResolvesToOverrideWithParams.cs:line 110
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams.CheckCall(SyntaxNode node, ArgumentListSyntax argumentList, SyntaxNodeAnalysisContext context) in C:\SourcesTv\temp\sonarlint-vs\src\SonarLint.CSharp\Rules\InvocationResolvesToOverrideWithParams.cs:line 112
   at SonarLint.Rules.CSharp.InvocationResolvesToOverrideWithParams.<>c.<Initialize>b__10_1(SyntaxNodeAnalysisContext c) in C:\SourcesTv\temp\sonarlint-vs\src\SonarLint.CSharp\Rules\InvocationResolvesToOverrideWithParams.cs:line 77
   at SonarLint.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c) in C:\SourcesTv\temp\sonarlint-vs\src\SonarLint\Helpers\DiagnosticAnalyzerContextHelper.cs:line 45
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by tvsonar** [comment]
Thanks @wilhelmmedetz for reporting this issue. Sorry for this inconvenience.

I believe this is the same as #714, I copied your stack trace there, and closed this issue.
